### ISSUE TITLE
1.20.1 Support

### ISSUE THREAD

**Issue by CrazyYaksha** [MattieOF/LeashableVillagers#1]
Tried to use on 1.20.1 and is not working, have you planned to port this to that version?

**Comment by mattiebw** [comment]
Sorry, completely forgot I made this lmao
I'm just starting uni so a little busy atm, but next time I find myself with nothing to do I'll try port it over!

**Comment by mattiebw** [comment]
Sorry for the wait, the mods been updated to 1.20.2! If you need a 1.20.1 version too, let me know and I'll throw that together quickly.

**Comment by mattiebw** [comment]
Did a 1.20.1 build regardless and seems to be getting even downloads so probably was a good idea haha
